### ISSUE TITLE
No Sound in minecraft 1.18 rc

### ISSUE THREAD

**Issue by Cristelknight999** [Sollace/Presence-Footsteps#110]
I updated to the new version r33 and now there isn't any sound. I downgraded it now to r32.

**Comment by RDKRACZ** [comment]
@Sollace The issue is the newest release does not have any sound files (no "sounds" folder in `/assets/presencefootsteps/` and `/assets/presencefootstepsmono/`). The first hint is the jar size - way smaller than the previous release. 
https://github.com/Sollace/Presence-Footsteps/commit/bed73687a68ce5fd02bb1a290fef8cbdf6980ceb targets the 1.18 branch, not 1.17.

**Comment by Sollace** [comment]
I have not release the mod for 1.18. You should not be trying to load it on there.

I see there was an issue with the last build (git decided to purge all the *.ogg files, so I'll quickly re-release it.

**Comment by Sollace** [comment]
New version is over here: https://github.com/Sollace/Presence-Footsteps/releases/tag/1.3.4
