### ISSUE TITLE
Volume control has no effect [1.4.0 - 1.18]

### ISSUE THREAD

**Issue by Xetheon** [Sollace/Presence-Footsteps#112]
The volume adjustment in the config doesn't give any noticeable change. The lowest setting at 3% has the same audio level as 100%

This is on version 1.4.0 of the mod for MC 1.18.

**Comment by Sollace** [comment]
Just tried it myself in 1.18 and the volume slider is working correctly. Is there anything else about your setup that I'm missing?

**Comment by GreyAsteroid** [comment]
I've had this happen to me and another user I'm playing with. It's not 100% of the time for either of us. Sometimes the config volume does nothing and we have to adjust player volume, other times it works correctly and we have to re-adjust the player volume to make up for it. We've been debugging another mod and have been relaunching Minecraft over and over so that's likely why we're running into it so often.

**Comment by Sollace** [comment]
I don't know what to say. There's nothing that would cause it to sometimes work and sometimes not. The value in the config is the same value that sets the position of the slider when you open the screen and it saves every time you change that.

If the config screen is saying it's 70% the value is definitely 70%.
