### ISSUE TITLE
do you have the permission to use those sounds from dynamic surroundings?

### ISSUE THREAD

**Issue by Y3Z0N** [Sollace/Presence-Footsteps#124]
s the title says you use the sounds of IFX and Dynamic Surroundings i wonder if you have the license to use those sounds.

**Comment by Y3Z0N** [comment]
you also use code from Dynamic Surroundings which have a different license... well explain.

**Comment by Sollace** [comment]
Presence Footsteps is the _original_ footsteps mod. [It has existed since 2013](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1290546-presence-footsteps-an-overly-complicated-sound) (long before Dynamic surroundings was ever published, going by their curseforge page) I have never used that mod, nor even known of its existance until now, so no, I have not used anything from them.

If anything, they are stealing _from me_. I have no issue with other people using the assets from this mod for their own project, and can easily prove to you that I have permission from @Hurricaaane to continue maintaining this project, but I draw the line at people accusing me of stealing my own cod.e

If you do see similaries to code in this repository, please report them as that is a copyright infringement of _this_ repository.
