### ISSUE TITLE
Please don't tell me this isn't a copy-paste of sounds from Dynamic Surroundings

### ISSUE THREAD

**Issue by SoftGuardian** [Sollace/Presence-Footsteps#125]

**Comment by Sollace** [comment]
Presence Footsteps has existed for several years before Dynamic Surroundings. This is the first time I've even heard of that mod, so if anyone is stealing anything, it's them.

**Comment by Y3Z0N** [comment]
Well thats quite strange if you did not copy code or assets then you maybe should report OreCruncher. sinc ehis mod is 2015 with a different license and use of your assets..

**Comment by Sollace** [comment]
I did take some time to look at his repo, but I don't really see any similarity, tbh. Its functionality has more in common with [MAtmos](https://github.com/Sollace/MAtmos) (ironically, a much older, now discontinued, mod) than it does with this one.

I won't pursue anything relating to the audio files alone, since I'm not really concerned if people want to use them. Huricaaane never told me where all of them came from, but I suspect you can find almost all of them in free online audio libraries (much like the places Minecraft got its own sounds in the early days).
