### ISSUE TITLE
1.19 has double jump sound and strange behavior when you are on basalt

### ISSUE THREAD

**Issue by EGOIST1372** [Sollace/Presence-Footsteps#153]
when you jump you can hear 2 times the sound of feet and it's odd.
also jumping on basalt is strange and in subtitle says ice cracks?!
![image](https://user-images.githubusercontent.com/86555131/173829136-2db8691d-372d-4820-ac08-b12eb543fa21.png)

**Comment by Mathead253** [comment]
Thank you for posting this, I thought the double jump sound was just me.

**Comment by Sollace** [comment]
Just tested and basalt sounds fine. The crack sound is intentional, because basalt is crumbly.

**Comment by EGOIST1372** [comment]
@Sollace so what about double jump? When you try jump multiple time on a
block you can hear double jump sounds

**Comment by Sollace** [comment]
@EGOIST1372 There is a sound when you jump and a sound when you land. As far as I can tell, it is working the way it's meant to be.

**Comment by Sollace** [comment]
I have changed the sounds for basalt.

**Comment by Sollace** [comment]
@EGOIST1372 I looked the second video, and the immediate problem is you're not actually standing _on_ the block. You're only a tiny bit on the edge of it and the rest of your body is over the air block beside it. The mod looks at the block nearest under you, and in that video, the block under you is air, so it definitely should not be making any step sounds there.

The other issues I've looked at, but this one I really don't believe is something that I can fix because of what a small edge case it is.

**Comment by EGOIST1372** [comment]
@Sollace I will test it in vanilla and report back. if it's vanilla then I will report it to the mojang. for now you can close this issue since you fixed both basalt and double sound. this is a side bug that as you said it's a fringe case and effects noone. just doing it for curiosity.

**Comment by Sollace** [comment]
It's very likely due to how it's rounding the value when you're on the edge.

If the block you're standing on is at an X value of 1 (so it's hitbox is from x=1 to x=2), if you're standing on it at 1.9 that will round to 1, and if you're standing on it at 0.9 it will round to 0.

> I will test it in vanilla and report back. if it's vanilla then I will report it to the mojang. for now you can close this issue since you fixed both basalt and double sound. this is a side bug that as you said it's a fringe case and effects noone. just doing it for curiosity.

Alright, cool. Thanks for your patience and for helping diagnose the issue. I'll get an update out with the fixes so far in the meantime...And might as well port back to 1.18 too ~~so people will stop making issues about it.~~

**Comment by EGOIST1372** [comment]
@Sollace 
I forgot how bad is vanilla sounds lol
it doesn't even create a jump sound on blocks when you stationary and jumping xD
it is probably what you said about the calculations. so this case is closed as well
and thanks you so much that listened and didn't ignore me. I've seen many devs do that even tho there is a bug. you've been patient and I appreciate it <3
