### ISSUE TITLE
[Bug?] Walking on carpet

### ISSUE THREAD

**Issue by Cymophic** [Sollace/Presence-Footsteps#167]
Carpet makes the walking sound of the block underneath it instead of the actual wool sound, which is slightly bothering especially when you are walking on carpeted flooring in an ancient city and your footsteps still make a lot of noise.

**Comment by Sollace** [comment]
Is this relating to modded carpets?

Any blocks like fences and carpets need to have sounds defined using the correct subtrate for Presence Footsteps to know how to treat them. Fences have the `.bigger` substrate, and carpets have `.carpet`. Otherwise, because they're very small the mod will ignore them and play the block that's below.

**Comment by Cymophic** [comment]
They were normal Minecraft carpets
