### ISSUE TITLE
Settings for this mod are not saved every time its turned off or relaunching minecraft

### ISSUE THREAD

**Issue by Mudxiej** [Sollace/Presence-Footsteps#202]
Every time, I disable this mod in MultiMC it's not saving the settings that I chose

**Comment by Sollace** [comment]
Sounds like a known bug in the config library Presence Footsteps uses. IIRC it's fixed in the upstream, so it will probably be fixed whenever I get to putting out an update.

Workaround for now is to install the latest Kirin for your version from here: https://github.com/MineLittlePony/Kirin/releases
