### ISSUE TITLE
Incorrect sound is used

### ISSUE THREAD

**Issue by Kib417** [Sollace/Presence-Footsteps#241]
When I walk on top of certain blocks instead of it using the stone noise or something it uses the wood noise. It usually happens with modded blocks but sometimes happens with vanilla blocks.

**Comment by Sollace** [comment]
I need specific examples otherwise I can't do anything.

Mods in general are responsible for assigning correct sound categories for their blocks.

Presence Footsteps also will produce sounds for all four blocks you're standing over, so if you're standing between a wood and stone block, it will produce either wood or stone, or both. That's the intended behaviour.
