### ISSUE TITLE
Player footsteps play when not moving

### ISSUE THREAD

**Issue by LivingSkeleton11** [Sollace/Presence-Footsteps#284]
I've noticed that my footsteps play even when I'm standing perfectly still. It seems random as well - it can be anywhere from 2 seconds to less than a quarter between the sounds. I'm sure that there are no other mobs around to play the sounds.

**Comment by LivingSkeleton11** [comment]
No, they continue to play for long after since I've stopped moving, and don't stop

**Comment by Sollace** [comment]
What version are you using?

I have had no one else report and issue like this.

**Comment by LivingSkeleton11** [comment]
I tested it with just Presence and I was wrong, it isn't Presence causing the issue. Apologies! However, there's another issue - the mod doesn't work for me at all. There are none of the custom footstep sounds. I'll be making a new ticket about that issue.

**Comment by Sollace** [comment]
> I tested it with just Presence and I was wrong, it isn't Presence causing the issue. Apologies! However, there's another issue - the mod doesn't work for me at all. There are none of the custom footstep sounds. I'll be making a new ticket about that issue.

Please do not. Make sure you have the built-in resource pack enabled first.

**Comment by Sollace** [comment]
Closing this per the previous comment. Thanks for confirming.

**Comment by LivingSkeleton11** [comment]
I just uninstalled Presence from my modpack and the ghost footsteps stopped. So it seems like there is an incompatibility somewhere, but I don't have any idea of what other mod it might be. The only other mod that comes to mind that would affect footsteps is Dynamic Surroundings, but I have tested it with that mod and there were no problems.

**Comment by Sollace** [comment]
> I just uninstalled Presence from my modpack and the ghost footsteps stopped. So it seems like there is an incompatibility somewhere, but I don't have any idea of what other mod it might be. The only other mod that comes to mind that would affect footsteps is Dynamic Surroundings, but I have tested it with that mod and there were no problems.

Sorry man, I don't really know then. I've been playing with Dynamic Surroundings in a modpack with over 500 other mods and haven't had such an issue so until I can reproduce it somehow there's nothing I can really do.

What you can do is tell me if you're running it on something other than 1.20.1, as the other versions don't recieve as much testing. It's entirely possible that there are issues which are specific to the minecraft version that I haven't caught. In specific, the current version uses a mixin to block entities from playing their normal sounds rather than setting the nextSteppingDistance to infinity which was done to fix the opposite issue.
