### ISSUE TITLE
Mod is heavily incompatible with Squake.

### ISSUE THREAD

**Issue by CharlieGamer4896** [Sollace/Presence-Footsteps#313]
every time i walk with squake enabled, it acts as if i'm running, and it's really irritating. I'm using specifically Re:Squake for 1.20.1, and it just really bothers me that i cant not walk like I'm slamming my feet into the ground.

**Comment by Sollace** [comment]
I have no idea what that is, but if you're walking faster than normal, that counts as running. You can edit the values with a resource pack and adding a [variator](https://github.com/Sollace/Presence-Footsteps/blob/1.20.5/src/main/resources/resourcepacks/default_sound_pack/assets/presencefootsteps/config/variator.json). Otherwise I don't know what I can really do from my end here.

Properties you can define are [over here](https://github.com/Sollace/Presence-Footsteps/blob/1.20.5/src/main/java/eu/ha3/presencefootsteps/config/Variator.java)
