### ISSUE TITLE
Blockmap Resource Pack Sound Overrides Not Functioning Correctly

### ISSUE THREAD

**Issue by YannDecelle** [Sollace/Presence-Footsteps#353]
**Issue Summary:**  
Greetings. I am encountering an issue while customizing the mod via a resource pack when running it through the Sinytra connector. Specifically, certain sound overrides in the blockmap do not function as expected.

---

**Details of the Issue:**

1. **Resource Pack Sound Override Behavior:**
   - The resource pack was created to modify block sounds within the mod. However, certain blocks and block tags are not responding to changes.

2. **Problematic Cases:**
   - **`minecraft:grass_block`:** Attempts to override the sound for this block are ignored. Despite the changes in the resource pack, the block continues to use the mod's default sound configuration.
   - **`#minecraft:nylium`:** Overrides for the tag `#minecraft:nylium` do not work. However, directly targeting individual blocks within the tag (e.g., `minecraft:crimson_nylium`) functions as expected.

3. **Observed Behavior:**
   - Blocks such as `minecraft:grass_block` and those within the `#minecraft:nylium` tag continue to produce the sounds specified by the mod, ignoring customizations defined in the resource pack.

4. **Working Cases:**
   - When targeting blocks like `minecraft:crimson_nylium` directly (not via tag), the sound override behaves as intended.

---

**Environment Information:**
- **Mod Loader/Connector:** Forge 47.3.12 + Sinytra Connector 1.0.0-beta.46. 
- **Customizations:** Custom resource pack

---

**Request for Clarification and Assistance:**
- Is this behavior expected when running the mod through the Sinytra connector? Could the connector be interfering with the proper application of resource pack overrides?
- Are there known limitations or constraints in the blockmap handling for certain blocks or tags (e.g., `minecraft:grass_block` or `#minecraft:nylium`)?
- Is there a workaround or best practice for ensuring that tag-based sound overrides are recognized?

---

Thank you for your time and expertise. I look forward to your insights on resolving this issue.

**Comment by YannDecelle** [comment]
Forgot to mention it does the same for fabric and forge with sinytra, and that both were in 1.20.1
Rolling back to PF 1.9.4 seem to fix the issue.

**Comment by Sollace** [comment]
Tags have lower priority than specific block ids. So if you have a sound mapping for a tag and a block within that tag, the sound for the named block will be used instead.

I'll have to see how I can possibly fix the overrides issue when it comes to resource packs. I did previously have the built in sounds loaded as a resource pack that people can enable/disable or change the order, but the built-in pack functionality in Quilt is buggy and I've had a lot of issues reported due to it so I've decided to revert back to having the sounds built into the mod instead.

**Comment by Sollace** [comment]
The load order was reversed (due to a previous issue). 

After switching it around to the correct order it's now working correctly, the below resource pack properly changes leaves to wood and grass to stone when placed at the top of the list.

```
{
    "minecraft:grass_block": "stone",
    "#minecraft:leaves": "wood"
}
```

Note that what I said before will still apply after the update, so pale oak leaves will still have their own sounds as they specify one that takes precedence over the tag. You'd have to manually redeclare it like this:
```
{
    "minecraft:grass_block": "stone",
    "#minecraft:leaves": "wood",
    "minecraft:pale_oak_leaves": "wood"
}
```

**Comment by YannDecelle** [comment]
Great ! 

Thanks for the fast answer !
