### ISSUE TITLE
Bats have footsteps

### ISSUE THREAD

**Issue by End0fw0r1d** [Sollace/Presence-Footsteps#46]
Figured I'd post because maybe it's unintentional, but bats make footsteps when their hitbox collides with the ground

**Comment by Sollace** [comment]
I'm aware of this, and a lot of other entities which aren't meant to have footsteps. This is because the features as they added in 1.15 are really just a "preview" of what I'm working on in 1.16 snapshots.

When it's done there will be a map specifically for mobs that defines whether they have 2/4/0 limbs so PF can generate the appropriate amount of footsteps.
