### ISSUE TITLE
Consider a port to Forge

### ISSUE THREAD

**Issue by Stryder914MC** [Sollace/Presence-Footsteps#60]
Alright, before I go on some sort of lengthy spiel here, I want to give some context on why I want this mod ported to Forge.
Before I moved up to 1.16.2, I typically played mod-packs on 1.12.2, as did a lot of people, and used a mod known as Dynamic Surroundings, which included Presence Footsteps in it's code.

Now, whenever I play modded Minecraft, it's just never felt the same. Minecraft now feels bland with a lack of really good ambience that truly made it feel alive. The only mod that comes close now is AmbientSounds 3. It's a really good ambience mod but it lacks the footstep noises that I came to love in Dynamic Surroundings, that really gave the kick to everything I did in game.

So, let the spiel begin. The reason I ask of you to consider porting to Forge isn't because of preference, but the preferences of others. I've been considering moving to Fabric for a while now, however, some of the mods for 1.16.2 that I play with, the authors have stated that they will not port to Fabric, or haven't directly stated but through action have given off that they won't. There are also some very awesome Fabric mods who's authors refuse to port to Forge.
As a result, I have two choices now. Either move to Fabric, and lock myself off from a stockpile of awesome mods, or stay on Forge, which locks me off from other awesome mods.

The likelihood of people finding some sort of bypass, either something that allows the loading of Fabric mods on the Forge modding platform is unlikely. I've read up on a couple of Reddit posts stating that even small Fabric mods that don't really affect gameplay is pushing it, or that's how I interpret the post.

And this isn't just about me. I have no doubts that there are a lot of people who want the same thing. If there's something that I'm missing here, which makes porting to Forge hard, or even impossible, then I'd love to know.
I'm not asking you to jump through flaming hoops just for one person. I'm only asking you to consider. Make up you're own mind on the matter, and come to your own conclusions.

**Comment by Sollace** [comment]
Hi there, though I appreciate the effort and the thought that went into this--believe me, I sympathise with your position--there are a number of technical and ethical reasons that make it so I cannot make a port to forge. Likely the same reason other developers can't support both or port to fabric as well.

First, the technical reason:

The long and short of it is that the Forge developers maintain a strict legal control over the use and distribution of MCP tools and names, especially so for the Searge mappings that contain all of the class names used in MCP. Even if the license explicitly allows one to use the mappings, Lex (forge developer) will still use any and all leverage he can to shut down competing projects or developers--something that is theorised to have already happened to Rift, and would have happened to Fabric if they had decided to use MCP mappings themselves.

Really, the only people allowed to use MCP are Forge and their close friends. As a result of this, Fabric has been forced to create their own mappings that are properly _truly_ free and open source. The sad side-effect of this is that forge and fabric mods cannot work together unless they can both be brought under the same mapping space--which, due to the above issues, would have to be fabric's Yarn mappings if they wanted any hope of staying independent of LexManos' influence.

The difference in mappings also makes maintaining two separate versions rather difficult, because the names largely disagree with each other, and the MCP names are more often than not completely wrong or misleading (one such case is memory/resource leak I was able to identify in Mine Little Pony only after porting to Yarn).

Luckily there are projects in the works moving towards a solution: 

Secondly is the moral reasons: [Patchwork](https://github.com/PatchworkMC) has the goal to create a version of Forge that runs on top of the fabric loader, and that would allow forge mods to be loaded alongside fabric mods using the Yarn mappings. I'm not following the development of that very closely, but the last time I checked a fully-functional release was still some ways away.

Supposedly it should be able to load simple forge mods just fine, though.

The second point is moral:

My history with forge, both as a normal player and a developer has been long and filled with hate. I do not agree with the way they behave, nor the way they have treated their userbase and developers. They are a group of self-righteous pricks founded on a legacy of strong-arming modders into giving them their code to make into a part of Forge.

They actively look down on everyone else, spit on their users, and any attempts at criticism are met with a ban from their Discord server. Because of this I do not wish to have anything to do with them or anything they have created.

**Comment by Stryder914MC** [comment]
Hey, thanks for getting back to me. And what you've told me about Forge today is the first time I've heard of any of this, and I'm appalled at Lex and the developers of Forge for their behavior. And now that I know, I understand 100% why you don't want to associate with them. And neither do I anymore. I'm hoping the developers of Patchwork can build a fully functional release. I'll take a gander at their GitHub page and if they've managed to make Patchwork functional, I'll most likely break away from using Forge and start using Fabric. Thank you for bringing this to my attention, both Patchwork and how Forge treats both it's developers and users.

**Comment by Sollace** [comment]
It's quite a pleasure. I'm glad you can understand. 👍
