### ISSUE TITLE
Resource pack won't work.

### ISSUE THREAD

**Issue by osmelious** [Sollace/Presence-Footsteps#67]
I'm trying to make a resource pack to add sounds to modded blocks, but no matter what I do the resource pack won't work, sounds won't change.

I made sure the blockmap.json file is in resourcepacks\PresenceFootsteps\assets\presencefootsteps\config
I've tried to make a resource pack with only the blockmap file in the directory, and I've tried a resource pack with all of the files, but neither worked.
To test it, I changed ["minecraft:stone": "stone"] to ["minecraft:stone": "wood"], which didn't work, and then I tried adding a new entry, which also didn't work.

I made sure to follow what the wiki said, though I couldn't troubleshoot it.
It's very possible that I'm just being dense, though any help would be appreciated.
Thanks. :)

**Comment by Sollace** [comment]
This is a known issue since other people have raised similar concerns on the curseforge page. I have a fix already implemented, you just have to wait until I have the time to do a build and release.

Keeping this opening until then, though.

**Comment by AvatarNeo12** [comment]
It's been over 4 years since the fix but I'm having the exact same problem on 1.21.1.  

I've tried it both as a folder and a .ZIP file, I tried with and without brackets and indentation in blockmap.json, and I've reloaded it a bunch of times. I only changed the materials for vanilla blocks, nothing else.

It only plays the default Presence Footsteps sounds.
